name: MongoDB C++ Driver CI/CD

on:
  push:
    branches:
      - main # Adjust to your repository's main branch

jobs:
  build:
    runs-on: ubuntu-latest # Choose the runner platform

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Package Repositories
        run: sudo apt-get update

      - name: Set up CMake and Build Essentials
        run: |
          sudo apt-get install -y cmake build-essential

      - name: Install Qt5 Development Libraries
        run: |
          sudo apt-get install -y qtbase5-dev

<<<<<<< HEAD
=======

>>>>>>> f341838997fa24fd3ac5ea3f1e4d307135411f9c
      - name: Build and Test Your Application
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ctest --output-on-failure
