name: C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Install CMake
        run: sudo apt-get install cmake

      - name: Build and Test
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ctest --output-on-failure
