name: C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Install CMake
        run: sudo apt-get install cmake

      - name: Install bsoncxx and mongocxx
        run: |
          curl -OL https://github.com/mongodb/mongo-cxx-driver/releases/download/r3.8.0/mongo-cxx-driver-r3.8.0.tar.gz
          tar -xzf mongo-cxx-driver-r3.8.0.tar.gz
          cd mongo-cxx-driver-r3.8.0/build

      - name: Install Qt5
        run: |
          sudo apt-get install -y qtbase5-dev

      - name: Build and Test
        run: |
          mkdir build
          cd build
          cmake ..
          make
