name: C++ CI

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Install CMake
        run: brew install cmake

      - name: Install OpenSSL
        run: brew install openssl

      - name: Install Qt5 
        run: |
          brew install qt@5

      - name: Install MongoDB C++ Driver
        run: |
          git clone --branch r3.8.0 --depth 1 https://github.com/mongodb/mongo-cxx-driver.git
          cd mongo-cxx-driver/build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_PREFIX_PATH=/usr/local/opt/openssl
          make
          sudo make install

      - name: Build and Test
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ctest --output-on-failure
