name: MongoDB C++ Driver CI/CD

on:
  push:
    branches:
      - main  # Adjust to your repository's main branch

jobs:
  build:
    runs-on: ubuntu-latest   # Choose the runner platform

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Package Repositories
        run: sudo apt-get update

      - name: Set up CMake and Build Essentials
        run: |
          sudo apt-get install -y cmake build-essential

      - name: Install Qt5 Development Libraries
        run: |
          sudo apt-get install -y qtbase5-dev

      - name: Install libmongoc and libbson Development Packages
        run: sudo apt-get install -y libmongoc-1.0-0 libbson-1.0-0
    
      - name: Clone and Build MongoDB C++ Driver
        run: |
          git clone --branch r3.8.0 --depth 1 https://github.com/mongodb/mongo-cxx-driver.git
          cd mongo-cxx-driver/build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local
          make
          ctest --output-on-failure

      - name: Build and Test Your Application
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ctest --output-on-failure
